[package]
name = "aster_fsd_persistence"
version.workspace = true
description = "AsterFSD SeaORM repositories and authentication adapters."
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
aster_fsd_auth.workspace = true
aster_fsd_migration.workspace = true
aster_fsd_model.workspace = true
async-trait.workspace = true
chrono.workspace = true
log.workspace = true
sea-orm.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
