[package]
name = "aster_fsd_protocol_classic"
version.workspace = true
description = "Classic FSD draft 9 protocol backend."
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
aster_fsd_codec.workspace = true
aster_fsd_model.workspace = true
aster_fsd_protocol.workspace = true
tracing.workspace = true

[lints]
workspace = true
